server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/sq_cloud?characterEncoding=utf8&useSSL=false&serverTimezone=CTT&rewriteBatchedStatements=true
      username: root
      password: root123

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities    # 所有Entity别名类所在包

eureka:
  client:
    register-with-eureka: true #表示是否将自己注册进EurekaServer
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，单节点无所谓，集群必须设置为true才能配合ribboon使用负载均衡
    service-url:
      defaultZone: http://localhost:7001/eureka

